const test = require('node:test')
const assert = require('node:assert/strict')
const { createPostFormState, reducePostFormState } = require('./miniprogram/services/post-form-state')
const { selectDiscoverablePosts, formatPrice } = require('./miniprogram/services/post-list-state')
const { createPostListState, reducePostListState } = require('./miniprogram/services/post-list-state')

test('discovery filters reset pagination, preserve campus changes and reject stale results', () => {
  let state = createPostListState({ user: { profileCompleted: true, campusId: 'bupt-shahe' } })
  state = reducePostListState(state, { type: 'LOAD_START', token: 'old' })
  state = reducePostListState(state, { type: 'FILTER_CHANGE', direction: 'need', contentType: 'item', categoryIds: ['books'] })
  state = reducePostListState(state, { type: 'LOAD_SUCCESS', token: 'old', posts: [{ _id: 'stale' }] })
  assert.equal(state.posts.length, 0)
  state = reducePostListState(state, { type: 'CAMPUS_CHANGE', campusId: 'bupt-xitucheng' })
  assert.equal(state.direction, 'need'); assert.deepEqual(state.categoryIds, ['books'])
  state = reducePostListState(state, { type: 'FILTER_CHANGE', contentType: 'service', categoryIds: ['books'] })
  assert.deepEqual(state.categoryIds, [])
  assert.equal(state.campusId, 'bupt-xitucheng')
})

test('discovery drawer applies only on confirmation and service clears the item category', () => {
  const fs = require('node:fs'), vm = require('node:vm'), path = require('node:path')
  let page
  vm.runInNewContext(fs.readFileSync('miniprogram/pages/discover/index.js', 'utf8'), {
    require: name => require(path.resolve('miniprogram/pages/discover', name)), Page: value => { page = value },
  })
  page.data = { ...page.data }; page.setData = patch => Object.assign(page.data, patch)
  page.state = createPostListState(); page.load = () => {}
  page.openFilters()
  page.pickFilter({ currentTarget: { dataset: { key: 'categoryId', id: 'books' } } })
  assert.deepEqual(page.state.categoryIds, [])
  assert.equal(page.data.filterDraft.contentType, 'item')
  page.pickFilter({ currentTarget: { dataset: { key: 'categoryId', id: 'digital' } } })
  assert.equal(page.data.filterDraft.categoryIds.join(','), 'books,digital')
  page.pickFilter({ currentTarget: { dataset: { key: 'categoryId', id: 'books' } } })
  assert.equal(page.data.filterDraft.categoryIds.join(','), 'digital')
  page.pickFilter({ currentTarget: { dataset: { key: 'categoryId', id: '' } } })
  assert.equal(page.data.filterDraft.categoryIds.length, 0)
  page.closeFilters(); page.openFilters()
  assert.equal(page.data.filterDraft.categoryIds.length, 0)
  page.pickFilter({ currentTarget: { dataset: { key: 'contentType', id: 'service' } } })
  page.confirmFilters()
  assert.equal(page.state.contentType, 'service'); assert.deepEqual(page.state.categoryIds, [])
  assert.equal(page.data.filterOpen, false)
})
test('stage2 form switches content types without losing either draft', () => {
  let state = createPostFormState()
  state = reducePostFormState(state, { type: 'PATCH_FORM', patch: { title: '我的商品' } })
  state = reducePostFormState(state, { type: 'SWITCH_KIND', direction: 'provide', contentType: 'service' })
  assert.equal(state.form.contentType, 'service')
  state = reducePostFormState(state, { type: 'PATCH_FORM', patch: { title: '我的服务', campusId: '' } })
  state = reducePostFormState(state, { type: 'SWITCH_KIND', direction: 'provide', contentType: 'item' })
  assert.equal(state.form.title, '我的商品')
  state = reducePostFormState(state, { type: 'SWITCH_KIND', direction: 'provide', contentType: 'service' })
  assert.equal(state.form.title, '我的服务')
  assert.equal(state.form.campusId, '')
})
test('stage2 discovery includes active service and need, and blank budget is negotiable', () => {
  assert.equal(selectDiscoverablePosts([{ _id: 's', contentType: 'service', status: 'active' }, { _id: 'n', direction: 'need', status: 'active' }, { _id: 'x', availableQuantity: 0, status: 'active' }]).length, 2)
  assert.equal(formatPrice(null), '面议')
})
test('stage2 publishing clears that kind draft without losing another kind', () => {
  let state = createPostFormState({ form: { title: '已经发布', images: [{ tempPath: 'a.jpg' }] } })
  state = reducePostFormState(state, { type: 'SWITCH_KIND', direction: 'need', contentType: 'item' })
  state = reducePostFormState(state, { type: 'PATCH_FORM', patch: { title: '尚未发布' } })
  state = reducePostFormState(state, { type: 'SWITCH_KIND', direction: 'provide', contentType: 'item' })
  state = reducePostFormState(state, { type: 'SAVE_SUCCESS', post: { _id: 'p' } })
  state = reducePostFormState(state, { type: 'SWITCH_KIND', direction: 'need', contentType: 'item' })
  assert.equal(state.form.title, '尚未发布')
  state = reducePostFormState(state, { type: 'SWITCH_KIND', direction: 'provide', contentType: 'item' })
  assert.equal(state.form.title, '')
  assert.equal(state.form.images.length, 0)
})
